service: sls-rest-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  apiGateway:
    shouldStartNameWithService: true
  vpc: ${file(vpc/vpc-env.config.yml):vpc-${self:provider.stage}}
  timeout: 180

functions:
  createTodo:
    handler: handlers/todo.createTodo
    events:
      - http:
          path: todos
          method: post
  getOneTodo:
    handler: handlers/todo.getOneTodo
    events:
      - http:
          path: todos/{id}
          method: get
  getAllTodos:
    handler: handlers/todo.getAllTodos
    events:
      - http:
          path: todos
          method: get
  updateTodo:
    handler: handlers/todo.updateTodo
    events:
      - http:
          path: todos/{id}
          method: put
  deleteTodo:
    handler: handlers/todo.deleteTodo
    events:
      - http:
          path: todos/{id}
          method: delete

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
